MODULE INPUT_PARAM

  IMPLICIT NONE
  
  CHARACTER (LEN = 256)   :: OBS_PATH, SYN_PATH, SCAT_PATH, ATOM_PATH, ATMOSOUT_PATH 
  CHARACTER (LEN = 256)   :: ATMOSIN_PATH, NOISE_PATH, WEIGHTS_PATH, FREE_PATH
  CHARACTER (LEN = 256)   :: FILT_PATH, MODE

END MODULE INPUT_PARAM
