SUBROUTINE READ_FREE(LIST_FREE_PARAMS)

  USE CONS_PARAM
  USE INPUT_PARAM

  IMPLICIT NONE

  INTEGER, INTENT(IN OUT), DIMENSION(10)             :: LIST_FREE_PARAMS
  INTEGER                             :: I

  OPEN (UNIT=98, FILE = FREE_PATH, ACTION = "read")
  DO I = 1, 10
     READ (UNIT=98, FMT=*) LIST_FREE_PARAMS(I)   
  ENDDO
  CLOSE(98)
 

END SUBROUTINE READ_FREE
