SUBROUTINE READ_NOISE

USE INV_PARAM
USE INPUT_PARAM

IMPLICIT NONE

  CHARACTER (LEN = 256) :: Line = ' '
  
  OPEN (UNIT=97, FILE = NOISE_PATH, ACTION="read", FORM='formatted')
  READ (UNIT=97, FMT='(A)') Line
  READ (UNIT=97, FMT = *) NOISE(1), NOISE(2), NOISE(3), NOISE(4)
  CLOSE(97)
  

END SUBROUTINE READ_NOISE
