SUBROUTINE READ_WEIGHTS

USE INV_PARAM
USE INPUT_PARAM

IMPLICIT NONE

  CHARACTER (LEN = 256) :: Line = ' '
  
  OPEN (UNIT=97, FILE = WEIGHTS_PATH, ACTION="read", FORM='formatted')
  READ (UNIT=97, FMT='(A)') Line
  READ (UNIT=97, FMT = *) WEIGHTS(1), WEIGHTS(2), WEIGHTS(3), WEIGHTS(4)
  CLOSE(97)
  

END SUBROUTINE READ_WEIGHTS
