SUBROUTINE WRITE_FILTERS(FILTERS)

  USE CONS_PARAM
  USE INPUT_PARAM
  USE LINE_PARAM

  IMPLICIT NONE

  INTEGER                                           :: I
  REAL(DP) , DIMENSION(NUMW,NFILT)                  :: FILTERS


	OPEN (UNIT=97, FILE = FILT_PATH, ACTION="write", FORM='formatted')
	DO I = 1, NUMW
	WRITE (UNIT=97, FMT=*) FILTERS(I,:)
	ENDDO
	CLOSE(97)
END SUBROUTINE WRITE_FILTERS
